language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn versioneye:update
  - mvn clean cobertura:cobertura coveralls:report

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "JP/nwfbBK39aOTfWNWcyxZpXKR1GHBbSxwcWZjJkF61xnW5uT3yfDF0z81p0IuexsMjAIkE2NAuP1PiK1NmLqSLw5aWiF5CZrFyDMJihpvYH5EHEAzufuBxMSRQ9IMtyctGrnhfN4/5HrvC2y7gYdxM2q0faNWuGvth0JxkOCBho7cTZU9Pxgl6iJyBt2yqj+fRaSQ6RgAiAnQCPeQ3T8FgtB5TRYgFbMMw3sQFamGPeSg0j4Cm6tpDOhcdznE/juCmkiNTehGRiXXWdd2O84OqQGShqHcWCBiC54jT5qu+zWBUKgSRzd1n/pES3OvPiEYa0FzHqjZ/TjrEsrJoHl6E4EqMzKuNl52gC5yWHbv+R+A7B3tr6M8KtpKoW6nsClNfhFtmlPp6p+SlQPR9YdCgVy8SQtNyMl/wuFmfbimVAn1WbLVmzwkbZwSmLAsoGMCIviNaYFsvwKEoNbpznQWb431j8+vOaz8rj6SwFsbRTYN8j9IqFY5ymQDwBjhstPQ4OdpPGVKsppPmsdXVY/JrFS0bpDKhNBCjuJkgoRLTAMtd+si4FGutMgjXjc5bCl7DmW+c7xQNBdon4THhpboV4JoT4IWGDD+eFseb9dWgfCmMQwi86oQ7bMpAnbt+DpxlREYE8C+9BAHTE+p3+h7iuTSpdia8ZOJbTXOVR1c0="

  addons:
    coverity_scan:
      project:
        name: "Iurii-Dziuban/spring-batch-sandbox"
        description: "Build submitted via Travis CI"
      notification_email: ydzyuban@gmail.com
      build_command_prepend: "mvn clean"
      build_command:   "mvn compile -DskipTests"
      branch_pattern: master